services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    restart: unless-stopped

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: attendance_db
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  mailhog:
    image: mailhog/
    ports:
      - "8025:8025"
    restart: unless-stopped

volumes:
  db-data:
